import React, { createContext, useState, useContext, useEffect } from 'react';
import { supabase } from '@/integrations/supabase/client';
import type { User, Session } from '@supabase/supabase-js';

type AppRole = 'admin' | 'teacher' | 'parent';

interface AuthContextType {
  isLoggedIn: boolean;
  user: User | null;
  session: Session | null;
  userName: string;
  userRole: AppRole | null;
  schoolId: string | null;
  loading: boolean;
  login: (email: string, password: string) => Promise<void>;
  signup: (email: string, password: string, schoolName: string) => Promise<string | null>;
  logout: () => Promise<void>;
  updateUserName: (name: string) => void;
  isAdmin: boolean;
  isTeacher: boolean;
}

const AuthContext = createContext<AuthContextType | null>(null);

export const AuthProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [user, setUser] = useState<User | null>(null);
  const [session, setSession] = useState<Session | null>(null);
  const [loading, setLoading] = useState(true);
  const [userName, setUserName] = useState('Admin User');
  const [userRole, setUserRole] = useState<AppRole | null>(null);
  const [schoolId, setSchoolId] = useState<string | null>(null);

  const fetchUserRole = async (userId: string) => {
    const { data } = await supabase
      .from('user_roles')
      .select('role, school_id')
      .eq('user_id', userId)
      .maybeSingle();
    setUserRole((data?.role as AppRole) ?? null);
    setSchoolId(data?.school_id ?? null);
  };

  useEffect(() => {
    const { data: { subscription } } = supabase.auth.onAuthStateChange((_event, session) => {
      setSession(session);
      setUser(session?.user ?? null);
      if (session?.user?.email) {
        setUserName(session.user.email.split('@')[0]);
      }
      if (session?.user?.id) {
        setTimeout(() => fetchUserRole(session.user.id), 0);
      } else {
        setUserRole(null);
        setSchoolId(null);
      }
      setLoading(false);
    });

    supabase.auth.getSession().then(({ data: { session } }) => {
      setSession(session);
      setUser(session?.user ?? null);
      if (session?.user?.email) {
        setUserName(session.user.email.split('@')[0]);
      }
      if (session?.user?.id) {
        fetchUserRole(session.user.id);
      }
      setLoading(false);
    });

    return () => subscription.unsubscribe();
  }, []);

  const login = async (email: string, password: string) => {
    const { error } = await supabase.auth.signInWithPassword({ email, password });
    if (error) throw error;
  };

  const signup = async (email: string, password: string, schoolName: string): Promise<string | null> => {
    // 1. Sign up the user
    const { data: authData, error: authError } = await supabase.auth.signUp({
      email,
      password,
      options: { emailRedirectTo: window.location.origin },
    });
    if (authError) throw authError;

    const userId = authData.user?.id;
    if (!userId) throw new Error('Signup failed - no user ID returned');

    // 2. Create a new school (school_code auto-generated by trigger)
    const { data: schoolData, error: schoolError } = await supabase
      .from('schools')
      .insert({ name: schoolName, school_code: 'TEMP' })
      .select('id, school_code')
      .single();
    if (schoolError) throw schoolError;

    // 3. Assign user role as admin for this school
    const { error: roleError } = await supabase
      .from('user_roles')
      .insert({ user_id: userId, role: 'admin' as const, school_id: schoolData.id });
    if (roleError) throw roleError;

    return schoolData.school_code;
  };

  const logout = async () => {
    const { error } = await supabase.auth.signOut();
    if (error) throw error;
  };

  const updateUserName = (newName: string) => {
    setUserName(newName);
  };

  const isAdmin = userRole === 'admin';
  const isTeacher = userRole === 'teacher';

  return (
    <AuthContext.Provider value={{ isLoggedIn: !!session, user, session, userName, userRole, schoolId, loading, login, signup, logout, updateUserName, isAdmin, isTeacher }}>
      {children}
    </AuthContext.Provider>
  );
};

export const useAuth = () => {
  const context = useContext(AuthContext);
  if (!context) throw new Error('useAuth must be used within AuthProvider');
  return context;
};
