// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://erapkeffzuagzzmpbypn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVyYXBrZWZmenVhZ3p6bXBieXBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIwOTQwMzQsImV4cCI6MjA4NzY3MDAzNH0.h-ezYjBsIfN7VIfHbScUSEK3NTSb5R2_rocpMc4BWKA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});